name: Release Docker images
on:
  release:
    types: [published]
jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
        with:
          token: ${{secrets.GOLANG_TOKEN}}
          submodules: recursive
      - name: Get Tag
        id: tag
        run: echo ::set-output name=TAG::$(echo $GITHUB_REF | cut -d / -f 3)
      # Setup docker build image
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      # Login to dockerhub
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      # Push development image
      - name: Push Local Static image to Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./providers/dev/dev.dockerfile
          push: true
          tags: |
            nitricimages/membrane-local:latest
            nitricimages/membrane-local:${{ steps.tag.outputs.TAG }}
      # Push AWS image
      - name: Push AWS Static image to Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./providers/aws/aws.dockerfile
          push: true
          tags: |
            nitricimages/membrane-aws:latest
            nitricimages/membrane-aws:${{ steps.tag.outputs.TAG }}
      # Push GCP image
      - name: Push GCP Static image to Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./providers/gcp/gcp.dockerfile
          push: true
          tags: |
            nitricimages/membrane-gcp:latest
            nitricimages/membrane-gcp:${{ steps.tag.outputs.TAG }}
      # Push Azure image
      - name: Push Azure Static image to Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./providers/azure/azure.dockerfile
          push: true
          tags: |
            nitricimages/membrane-azure:latest
            nitricimages/membrane-azure:${{ steps.tag.outputs.TAG }}
